package com.example.holoverse.ui.theme
import androidx.compose.ui.graphics.Color


val ColorGunmetal = Color(0xFF2C2B3F)
val ColorGunmetal50 = Color(0x802C2B3F)
val ColorVerdigris = Color(0xFF38DED2)
val ColorGraniteGray = Color(0xFF8E8E8E)
val ColorPlatinum = Color(0xFFE1E6E3)
val ColorAmericanPurple = Color(0xFF473FC4)
val ColorRed = Color(0xFFF51506)

val ColorBlue = Color(0xFF007AFF)

val HoloBlack = Color(0xFF050510)
val HoloCyan = Color(0xFF00E5FF)
val HoloPurple = Color(0xFFD500F9)
val GlassWhite = Color(0x1AFFFFFF)
val BorderWhite = Color(0x33FFFFFF)



val primaryLight = Color(0xFF585992)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE2DFFF)
val onPrimaryContainerLight = Color(0xFF414178)
val secondaryLight = Color(0xFF006A6A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF9CF1F0)
val onSecondaryContainerLight = Color(0xFF004F50)
val tertiaryLight = Color(0xFF865319)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDCBE)
val onTertiaryContainerLight = Color(0xFF6A3C01)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFCF8FF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFF5FAFB)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFE4E1EC)
val onSurfaceVariantLight = Color(0xFF47464F)
val outlineLight = Color(0xFF777680)
val outlineVariantLight = Color(0xFFC8C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFFC1C1FF)
val surfaceDimLight = Color(0xFFD5DBDC)
val surfaceBrightLight = Color(0xFFF5FAFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F6)
val surfaceContainerLight = Color(0xFFE9EFF0)
val surfaceContainerHighLight = Color(0xFFE3E9EA)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)

val primaryLightMediumContrast = Color(0xFF303066)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF6767A2)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF003D3D)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF167979)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF522D00)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF976126)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFCF8FF)
val onBackgroundLightMediumContrast = Color(0xFF1B1B21)
val surfaceLightMediumContrast = Color(0xFFF5FAFB)
val onSurfaceLightMediumContrast = Color(0xFF0C1213)
val surfaceVariantLightMediumContrast = Color(0xFFE4E1EC)
val onSurfaceVariantLightMediumContrast = Color(0xFF36353E)
val outlineLightMediumContrast = Color(0xFF52515B)
val outlineVariantLightMediumContrast = Color(0xFF6D6C75)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3133)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F3)
val inversePrimaryLightMediumContrast = Color(0xFFC1C1FF)
val surfaceDimLightMediumContrast = Color(0xFFC2C7C9)
val surfaceBrightLightMediumContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F6)
val surfaceContainerLightMediumContrast = Color(0xFFE3E9EA)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DEDF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD3D4)

val primaryLightHighContrast = Color(0xFF26255C)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF43437B)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF003232)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF005252)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF442400)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF6C3E03)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFCF8FF)
val onBackgroundLightHighContrast = Color(0xFF1B1B21)
val surfaceLightHighContrast = Color(0xFFF5FAFB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE4E1EC)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2C2B34)
val outlineVariantLightHighContrast = Color(0xFF494851)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B3133)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFC1C1FF)
val surfaceDimLightHighContrast = Color(0xFFB4BABB)
val surfaceBrightLightHighContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFECF2F3)
val surfaceContainerLightHighContrast = Color(0xFFDEE3E5)
val surfaceContainerHighLightHighContrast = Color(0xFFCFD5D6)
val surfaceContainerHighestLightHighContrast = Color(0xFFC2C7C9)

val primaryDark = Color(0xFFC1C1FF)
val onPrimaryDark = Color(0xFF2A2A60)
val primaryContainerDark = Color(0xFF414178)
val onPrimaryContainerDark = Color(0xFFE2DFFF)
val secondaryDark = Color(0xFF80D5D4)
val onSecondaryDark = Color(0xFF003737)
val secondaryContainerDark = Color(0xFF004F50)
val onSecondaryContainerDark = Color(0xFF9CF1F0)
val tertiaryDark = Color(0xFFFDB975)
val onTertiaryDark = Color(0xFF4A2800)
val tertiaryContainerDark = Color(0xFF6A3C01)
val onTertiaryContainerDark = Color(0xFFFFDCBE)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDEE3E5)
val surfaceVariantDark = Color(0xFF47464F)
val onSurfaceVariantDark = Color(0xFFC8C5D0)
val outlineDark = Color(0xFF918F9A)
val outlineVariantDark = Color(0xFF47464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2B3133)
val inversePrimaryDark = Color(0xFF585992)
val surfaceDimDark = Color(0xFF0E1415)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF171D1E)
val surfaceContainerDark = Color(0xFF1B2122)
val surfaceContainerHighDark = Color(0xFF252B2C)
val surfaceContainerHighestDark = Color(0xFF303637)

val primaryDarkMediumContrast = Color(0xFFDBD9FF)
val onPrimaryDarkMediumContrast = Color(0xFF1F1F55)
val primaryContainerDarkMediumContrast = Color(0xFF8B8BC8)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFF96EBEA)
val onSecondaryDarkMediumContrast = Color(0xFF002B2B)
val secondaryContainerDarkMediumContrast = Color(0xFF479E9D)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFD5AF)
val onTertiaryDarkMediumContrast = Color(0xFF3B1F00)
val tertiaryContainerDarkMediumContrast = Color(0xFFC08446)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF131318)
val onBackgroundDarkMediumContrast = Color(0xFFE4E1E9)
val surfaceDarkMediumContrast = Color(0xFF0E1415)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF47464F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDEDBE6)
val outlineDarkMediumContrast = Color(0xFFB3B0BB)
val outlineVariantDarkMediumContrast = Color(0xFF918F99)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2C)
val inversePrimaryDarkMediumContrast = Color(0xFF424279)
val surfaceDimDarkMediumContrast = Color(0xFF0E1415)
val surfaceBrightDarkMediumContrast = Color(0xFF3F4647)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF040809)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191F20)
val surfaceContainerDarkMediumContrast = Color(0xFF23292A)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2D3435)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF393F40)

val primaryDarkHighContrast = Color(0xFFF1EEFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFBDBDFD)
val onPrimaryContainerDarkHighContrast = Color(0xFF03003B)
val secondaryDarkHighContrast = Color(0xFFAAFFFE)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF7CD1D0)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E0E)
val tertiaryDarkHighContrast = Color(0xFFFFEDDF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFF9B572)
val onTertiaryContainerDarkHighContrast = Color(0xFF160800)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF131318)
val onBackgroundDarkHighContrast = Color(0xFFE4E1E9)
val surfaceDarkHighContrast = Color(0xFF0E1415)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF47464F)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF2EEFA)
val outlineVariantDarkHighContrast = Color(0xFFC4C1CC)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF424279)
val surfaceDimDarkHighContrast = Color(0xFF0E1415)
val surfaceBrightDarkHighContrast = Color(0xFF4B5152)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1B2122)
val surfaceContainerDarkHighContrast = Color(0xFF2B3133)
val surfaceContainerHighDarkHighContrast = Color(0xFF363C3E)
val surfaceContainerHighestDarkHighContrast = Color(0xFF424849)












